# Number of days of inactivity before an issue becomes stale
daysUntilStale: 15
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 30
# Issues with these labels will never be considered stale
exemptLabels:
  - "Status: Blocked"
  - "Type: Release"
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Estamos marcando como STALE este item pois está desatualizado por falta de
  atividades recentes!
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: true