language: java
jdk:
  - openjdk8

install: true

os:
  - linux

branches:
  only:
    - master

script:
- sbt test
- sbt publishLocal

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"
    
before_cache:
  - rm -rf $HOME/.ivy2/local
  - rm -rf $HOME/.ivy2/cache/justa.com.vc/*
  - rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/justa.com.vc/*
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt  -name "*.lock"               -delete

notifications:
  email:
    recipients:
      - it-recife@justa.com.vc
