language: java
jdk:
  - openjdk8

install: true
 
script:
- sbt test
- mvn deploy

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"
    
before_cache:
  - rm -rf $HOME/.ivy2/local
  - rm -rf $HOME/.ivy2/cache/com.typesafe.play/*
  - rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt  -name "*.lock"               -delete
