language: scala
scala:
  - 2.13.3
  - 2.12.13

os:
  - linux

jdk:
  - oraclejdk11

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean compile test

cache:
  directories:
    - $HOME/.ivy2/cache

before_cache:
  # Ensure changes to the cache aren't persisted
  - rm -rf $HOME/.ivy2/cache/justa.com.vc
  - rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/justa.com.vc
  - rm -rf $HOME/.ivy2/cache/com.github.justapagamentos
  - rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.github.justapagamentos

  # Delete all ivy data files since ivy touches them on each build
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
