language: java
jdk:
  - openjdk8

install: true

branches:
  only:
    - master

script:
- sbt test
- sbt dist
- sbt -Dbintray.user=$BINTRAY_USER -Dbintray.pass=$BINTRAY_PASS publish

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"
    
before_cache:
  - rm -rf $HOME/.ivy2/local
  - rm -rf $HOME/.ivy2/cache/com.typesafe.play/*
  - rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt  -name "*.lock"               -delete

notifications:
  email:
    recipients:
      - it-recife@justa.com.vc